version: 0.2
env:
  variables:
    APP_NAME: "bike-builder-front-end"
    BRANCH: "main"
phases:
  install:
    runtime-versions:
      nodejs: 14.x
    commands:
      - echo install process started
      - if [ -z "${BRANCH}" ]; then echo "BRANCH not set" && exit 1 ; fi
      - npm install && npm install -g @angular/cli
  build:
    commands:
      - echo build process started now
      - git checkout $BRANCH
      - ng build
  post_build:
    commands:
      - echo build process finished, we should upload to S3 now
      - cd dist/$APP_NAME
      - ls -la
      - aws s3 sync . s3://bike-builder-front-end/$ENVIRONMENT --delete
